# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: my-tpc

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      set -x       
      #!/bin/bash 
      # Create keytab file
      #user="SVC-SSMANDROID"
      #pass='Mu!i^dC)n!B
      #printf "%b" "addent -password -p SVC-SSMANDROID -k 1 -e RC4-HMAC\nMu!i^dC)n!B\nwkt SVC-SSMANDROID" | ktutil
      printf "%b" "addent -password -p $(user) -k 1 -e RC4-HMAC\n$(pass)\nwkt $(user).keytab" | ktutil
      quit
      mv  $(user).keytab ~./test/
    

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

# - task: Docker@2
#   inputs:
#     containerRegistry: 'localacr'
#     repository: 'node-docker'
#     command: 'buildAndPush'
#     Dockerfile: '**/Dockerfile'
#     tags: 'latest'
